### ISSUE TITLE
Issue with MRM function - incorrect number of dimension

### ISSUE THREAD

**Issue by GuillaumeSwB** [phiala/ecodist#5]
Hi, 

I would like to report an issue when trying to use the MRM function (ecodist package 2.0.9 in RStudio 2022.02.3 Build 492 on MacOS Catalina) through the example provided in the package documentation.

> data(graze)
> MRM(dist(LOAR10) ~ dist(sitelocation) + dist(forestpct), data=graze, nperm=10)
Error in xj[i, , drop = FALSE] : incorrect number of dimensions

I also tried to apply this function on personal data, without success.

Thank you in advance for your help,

Best regards

Guillaume

**Comment by sgoslee** [comment]
Hi,

That's most likely the same problem as reported here: https://stackoverflow.com/questions/68310302/incorrect-dimensions-error-with-the-function-mrm-in-the-package-ecodist

It appears to be caused by having other packages loaded, notably spdep. MRM() works correctly in a vanilla R session on CRAN, and on every platform I have available to test on. 

I have not, however, been able to figure out exactly what is going on and come up with a way to fix it. It's something to do with the implicit coercion to vector within the formula interface. 

There is a work-around, though, which is to explicitly coerce the distance objects to vectors before using MRM (here then to data frame columns for convenience).


# Explicit conversion to vector

graze.d <- with(graze, data.frame(LOAR10 = as.vector(dist(LOAR10)), sitelocation = as.vector(dist(sitelocation)), forestpct = as.vector(dist(forestpct))))

MRM(LOAR10 ~ sitelocation + forestpct, data=graze.d, nperm=10)

**Comment by simoncarrignon** [comment]
Hello! should this issue really be closed? I understand it's not a problem from the package but it still happens (it's happening to me while trying to do some mantel test). Maybe it should stay open until the (terrible) package that manipulates `dist` in such a bad way stop  doing that, or that the workaround (using the vector instead of distance did solve the problem for me to!) is somehow implementend if/when needed? I didn't have   time too look more carefully if it's indeed the fault of `sdep` for me too (wouldn't be suprise tho) but may spend a few hours on that if i can. Then i can maybe open an issue wherever sdep issues can be open and also help looking at integrating the quick 'as.vector' patch when needed!

**Comment by SarahGoslee-USDA** [comment]
Simon, is it failing if you use the development version of ecodist (installed from github)?

The version on CRAN does not have the fix I added, but the development version will be sent to CRAN within the next week or so with assorted new improvements, including a (less than ideal) fix for the package that overwrites the dist method.

**Comment by SarahGoslee-USDA** [comment]
To document this more fully, the cause of the error is in the proxy package (thanks to Peter Dalgaard for tracking that down): 

proxy::dim.dist, changes the default behavior of dim()

The maintainer of proxy is working on a update that removes the non-standard behavior; the main reason I didn't push the update to CRAN is that I was hoping the fix to proxy itself would come about soon. 

The function I added to the development version of ecodist returns the dim.dist behavior to the base default, but only if ecodist is loaded after proxy. This may then break proxy, but that wasn't a big concern of mine.

Unfortunately, since it comes from a different loaded package, it isn't something I can actually fix completely. Here's hoping for a proxy update.

**Comment by simoncarrignon** [comment]
(responding to your previous post): ooh sorry yeah I didn't try to install the github version ; i didn't get you added something in the dev version as i just saw that the OP closed the issue after saying the workaround was working for him... will give it a go as soon as I have time! thanks for all the good work anyway!!
